#!/usr/bin/env python3
"""
10_gap9_random_demo.py

Randomized TinyDisasterVQA GAP9 demo.

This script:
  1. Randomly chooses a pre-generated demo sample.
  2. Copies its Input_1.bin / Input_2.bin into the generated GAP9 app root.
  3. Prints image/question/ground-truth/reference prediction.
  4. Runs the GAP9 generated executable through CMake.

Assumption:
  demo_inputs were already generated by scripts/09_make_gap9_demo_input.py.

Example inside Docker:

  cd /app/TinyDisasterVQA
  PYTHONPATH=src python scripts/10_gap9_random_demo.py \\
    --model-dir gap9_generated_final/tdm_fast_128_ce_best \\
    --platform gvsoc

For physical board:

  PYTHONPATH=src python scripts/10_gap9_random_demo.py \\
    --model-dir gap9_generated_final/tdm_fast_128_ce_best \\
    --platform board
"""

from __future__ import annotations

import argparse
import json
import random
import shutil
import subprocess
from pathlib import Path


def parse_args():
    p = argparse.ArgumentParser()

    p.add_argument(
        "--model-dir",
        type=Path,
        default=Path("gap9_generated_final/tdm_fast_128_ce_best"),
        help="Generated GAP9 model directory.",
    )
    p.add_argument(
        "--platform",
        choices=("gvsoc", "board"),
        default="gvsoc",
        help="Only used for display. Configure menuconfig manually before running if needed.",
    )
    p.add_argument(
        "--seed",
        type=int,
        default=None,
        help="Optional random seed for reproducibility.",
    )
    p.add_argument(
        "--sample-dir",
        type=Path,
        default=None,
        help="Use a specific sample directory instead of random selection.",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Prepare and print sample, but do not run CMake.",
    )

    return p.parse_args()


def find_demo_samples(model_dir: Path) -> list[Path]:
    demo_inputs = model_dir / "demo_inputs"

    if demo_inputs.exists():
        samples = sorted(
            path for path in demo_inputs.iterdir()
            if path.is_dir() and (path / "demo_expected.json").exists()
        )
        if samples:
            return samples

    if (model_dir / "demo_expected.json").exists():
        return [model_dir]

    raise FileNotFoundError(
        f"No demo samples found. Expected either:\n"
        f"  {demo_inputs}/sample_*/demo_expected.json\n"
        f"or:\n"
        f"  {model_dir / 'demo_expected.json'}"
    )


def load_info(sample_dir: Path) -> dict:
    path = sample_dir / "demo_expected.json"
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def copy_inputs_to_model_root(sample_dir: Path, model_dir: Path) -> None:
    required = ["Input_1.bin", "Input_2.bin", "demo_expected.json"]

    for name in required:
        src = sample_dir / name
        if not src.exists():
            raise FileNotFoundError(f"Missing {src}")

        shutil.copy2(src, model_dir / name)

    optional = [
        "Input_1_float32.bin",
        "Input_1_uint8.bin",
        "Input_2_onehot_float32.bin",
        "Input_2_onehot_uint8.bin",
        "Input_2_question_template_id.bin",
    ]

    for name in optional:
        src = sample_dir / name
        if src.exists():
            shutil.copy2(src, model_dir / name)


def check_input_sizes(model_dir: Path) -> None:
    input_1 = model_dir / "Input_1.bin"
    input_2 = model_dir / "Input_2.bin"

    size_1 = input_1.stat().st_size
    size_2 = input_2.stat().st_size

    print()
    print("Input binary sizes:")
    print(f"  Input_1.bin: {size_1} bytes")
    print(f"  Input_2.bin: {size_2} bytes")

    if size_1 != 49152:
        print("  [WARN] Input_1.bin is not 49152 bytes. Expected uint8 [1,3,128,128].")

    if size_2 != 124:
        print("  [WARN] Input_2.bin is not 124 bytes. Expected float32 one-hot [1,31].")


def run_gap9(model_dir: Path) -> int:
    print()
    print("=" * 80)
    print("Running GAP9 generated app")
    print("=" * 80)

    cmd = ["cmake", "--build", "build", "--target", "run"]

    proc = subprocess.run(
        cmd,
        cwd=model_dir,
        text=True,
    )

    return int(proc.returncode)


def print_demo_header(info: dict, sample_dir: Path, model_dir: Path, platform: str) -> None:
    print("=" * 80)
    print("TinyDisasterVQA randomized GAP9 demo")
    print("=" * 80)
    print(f"Model dir:       {model_dir}")
    print(f"Platform:        {platform}")
    print(f"Sample dir:      {sample_dir}")
    print()
    print("Selected sample:")
    print(f"  Row index:     {info.get('row_index')}")
    print(f"  Image:         {info.get('image_path')}")
    print(f"  Question:      {info.get('question')}")
    print(f"  Template id:   {info.get('question_template_id')}")
    print(f"  Question type: {info.get('question_type')}")
    print(f"  Edge head:     {info.get('edge_head')}")
    print()
    print("Reference labels/predictions:")
    print(f"  Ground truth class: {info.get('target_edge_global')} ({info.get('answer')})")
    print(f"  PyTorch argmax:     {info.get('pytorch_argmax')}")
    print(f"  ONNX argmax:        {info.get('onnx_argmax')}")
    print(f"  PyTorch/ONNX match: {info.get('prediction_match_pytorch_onnx')}")
    print()
    print("Note:")
    print("  The generated GAP9 app currently prints execution/profiling information.")
    print("  The class prediction shown above is the PyTorch/ONNX reference for the same input.")
    print("  GAP9 success is indicated by 'Runner completed: 0' and the cycle table.")


def main() -> None:
    args = parse_args()

    model_dir = args.model_dir.resolve()

    if not model_dir.exists():
        raise FileNotFoundError(f"Missing model directory: {model_dir}")

    if args.seed is not None:
        random.seed(args.seed)

    if args.sample_dir is not None:
        sample_dir = args.sample_dir.resolve()
        if not sample_dir.exists():
            raise FileNotFoundError(f"Missing sample directory: {sample_dir}")
    else:
        samples = find_demo_samples(model_dir)
        sample_dir = random.choice(samples).resolve()

    info = load_info(sample_dir)

    print_demo_header(
        info=info,
        sample_dir=sample_dir,
        model_dir=model_dir,
        platform=args.platform,
    )

    copy_inputs_to_model_root(sample_dir=sample_dir, model_dir=model_dir)
    check_input_sizes(model_dir)

    if args.dry_run:
        print()
        print("[DRY RUN] Prepared inputs but did not launch GAP9.")
        return

    ret = run_gap9(model_dir)

    print()
    print("=" * 80)
    if ret == 0:
        print("Demo complete: GAP9 app finished successfully.")
    else:
        print(f"Demo finished with non-zero return code: {ret}")
    print("=" * 80)

    raise SystemExit(ret)


if __name__ == "__main__":
    main()